import { Pressable, View } from "react-native";
import { useRouter, type Href } from "expo-router";
import Svg, { Circle, Path, Rect } from "react-native-svg";
import { LinearGradient } from "expo-linear-gradient";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { AppText, EWasteHero, PortalThemeProvider, tokens } from "@rebin/ui";

/**
 * Splash-only backdrop: a mint wash plus oversized leaf silhouettes bled off
 * the corners. Kept local to this screen — the rest of the app sits on the
 * flat cream `tokens.color.bg`, and only the first impression gets the
 * ambient treatment.
 */
function SplashBackdrop() {
  return (
    <View pointerEvents="none" style={{ position: "absolute", inset: 0 }}>
      <LinearGradient
        colors={["#FBFDFA", "#F2F8F1", "#EAF4EA"]}
        start={{ x: 0.1, y: 0 }}
        end={{ x: 0.9, y: 1 }}
        style={{ position: "absolute", inset: 0 }}
      />
      <Svg width="100%" height="100%" viewBox="0 0 400 800" style={{ position: "absolute", inset: 0 }}>
        {/* top-left leaf, bled off the corner */}
        <Path
          d="M-40 -20 C60 -30 130 40 120 140 C40 120 -20 70 -40 -20 Z"
          fill={tokens.color.primary}
          opacity={0.06}
        />
        {/* bottom-right leaf */}
        <Path
          d="M440 820 C340 830 270 760 280 660 C360 680 420 730 440 820 Z"
          fill={tokens.color.primary}
          opacity={0.06}
        />
        {/* small drifting leaf, mid right */}
        <Path
          d="M356 300 c22 -18 46 -12 54 8 c-22 4 -38 16 -48 36 c-14 -14 -18 -32 -6 -44 z"
          fill={tokens.color.success}
          opacity={0.1}
        />
        {/* dotted grid, top right — echoes the reference's texture */}
        {[0, 1, 2, 3].map((r) =>
          [0, 1, 2, 3, 4].map((c) => (
            <Circle
              key={`${r}-${c}`}
              cx={318 + c * 18}
              cy={42 + r * 18}
              r="2.4"
              fill={tokens.color.primary}
              opacity={0.14}
            />
          )),
        )}
      </Svg>
    </View>
  );
}

// Same reasoning as RoleGuard.tsx's `asHref`: Expo Router's typed-routes
// codegen is generated by the dev server, not `tsc`, and the checked-in
// snapshot predates these routes. Every string passed through is a
// hand-authored, known route name, never unvalidated input.
function asHref(path: string): Href {
  return path as Href;
}

type FeatureKey = "certified" | "pickup" | "paid" | "impact";

const FEATURES: { key: FeatureKey; label: string; body: string }[] = [
  { key: "certified", label: "Certified & Secure", body: "Serial-tracked disposal" },
  { key: "pickup", label: "Doorstep Pickup", body: "We collect from you" },
  { key: "paid", label: "Earn from E-Waste", body: "Get paid for scrap" },
  { key: "impact", label: "Reduce Impact", body: "For a cleaner planet" },
];

function FeatureIcon({ feature, size = 24 }: { feature: FeatureKey; size?: number }) {
  const color = tokens.color.primary;
  if (feature === "certified") {
    return (
      <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
        <Path d="M12 3l7 3v6c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6z" fill={color} opacity={0.15} />
        <Path d="M12 3l7 3v6c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6z" stroke={color} strokeWidth="1.8" strokeLinejoin="round" />
        <Path d="M9 12l2 2 4-4.5" stroke={color} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
      </Svg>
    );
  }
  if (feature === "pickup") {
    return (
      <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
        <Path d="M2 8h11v8H2z" fill={color} opacity={0.15} />
        <Path d="M2 8h11v8H2z" stroke={color} strokeWidth="1.8" strokeLinejoin="round" />
        <Path d="M13 11h4l4 3v2h-8z" stroke={color} strokeWidth="1.8" strokeLinejoin="round" />
        <Circle cx="6.5" cy="18" r="1.8" stroke={color} strokeWidth="1.8" />
        <Circle cx="17.5" cy="18" r="1.8" stroke={color} strokeWidth="1.8" />
      </Svg>
    );
  }
  if (feature === "paid") {
    return (
      <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
        <Rect x="2" y="6" width="20" height="14" rx="2" fill={color} opacity={0.15} />
        <Rect x="2" y="6" width="20" height="14" rx="2" stroke={color} strokeWidth="1.8" />
        <Path d="M2 10h20" stroke={color} strokeWidth="1.8" />
        <Circle cx="17" cy="15" r="1.7" fill={color} />
      </Svg>
    );
  }
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Circle cx="12" cy="12" r="9" fill={color} opacity={0.15} />
      <Circle cx="12" cy="12" r="9" stroke={color} strokeWidth="1.8" />
      <Path d="M12 3c2.5 2.5 2.5 15.5 0 18M3 12h18" stroke={color} strokeWidth="1.3" opacity={0.55} />
      <Path d="M15 7c2 1 2.5 3.5 1 5.5-2-.2-3.3-1.7-3.3-3.7 0-.8.9-1.5 2.3-1.8z" fill={color} />
    </Svg>
  );
}

export default function Index() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  return (
    <PortalThemeProvider portal="org">
      <View style={{ flex: 1, backgroundColor: "#FBFDFA" }}>
        <SplashBackdrop />
        <View
          style={{
            flex: 1,
            paddingTop: insets.top + tokens.space[3],
            paddingBottom: insets.bottom + tokens.space[3],
            paddingHorizontal: tokens.space[4],
            gap: tokens.space[3],
            justifyContent: "center",
          }}
        >
          {/* Wordmark */}
          <View style={{ alignItems: "center", gap: 2 }}>
            <AppText variant="h2" style={{ letterSpacing: 0.5 }}>
              REBIN<AppText variant="h2" tone="accent">TECH</AppText>
            </AppText>
            <AppText variant="label" tone="muted" style={{ letterSpacing: 1.5, fontSize: 8 }}>
              E-WASTE RECYCLING
            </AppText>
          </View>

          {/* Headline */}
          <View style={{ alignItems: "center", gap: 1 }}>
            <AppText variant="display" style={{ textAlign: "center", fontSize: 25, lineHeight: 29 }}>
              Recycle Today.
            </AppText>
            <AppText variant="display" tone="accent" style={{ textAlign: "center", fontSize: 25, lineHeight: 29 }}>
              Protect Tomorrow.
            </AppText>
            <AppText variant="bodySm" tone="muted" style={{ textAlign: "center", maxWidth: 290, marginTop: 3 }}>
              Schedule e-waste pickup in minutes. Safe, certified and eco-friendly disposal.
            </AppText>
          </View>

          {/* Hero — the largest element on the screen */}
          <View style={{ alignItems: "center" }}>
            <EWasteHero size={240} />
          </View>

          {/* Feature grid */}
          <View style={{ flexDirection: "row", flexWrap: "wrap", gap: tokens.space[1] }}>
            {FEATURES.map((f) => (
              <View
                key={f.key}
                style={{
                  flexBasis: "47%",
                  flexGrow: 1,
                  alignItems: "center",
                  gap: 3,
                  paddingVertical: tokens.space[2],
                  paddingHorizontal: 6,
                  borderRadius: tokens.radius.card,
                  backgroundColor: tokens.color.surface,
                  shadowColor: "#16241C",
                  shadowOpacity: 0.06,
                  shadowRadius: 10,
                  shadowOffset: { width: 0, height: 3 },
                  elevation: 2,
                }}
              >
                <FeatureIcon feature={f.key} />
                <AppText variant="bodySm" style={{ fontWeight: "600", textAlign: "center", fontSize: 12 }}>
                  {f.label}
                </AppText>
                <AppText variant="label" tone="muted" style={{ fontSize: 8, textAlign: "center" }}>
                  {f.body}
                </AppText>
              </View>
            ))}
          </View>

          {/* CTA + trust line */}
          <View style={{ gap: tokens.space[2] }}>
            <Pressable
              accessibilityRole="button"
              accessibilityLabel="Get Started"
              onPress={() => router.push(asHref("/login"))}
              style={({ pressed }) => ({
                borderRadius: 32,
                overflow: "hidden",
                shadowColor: tokens.color.primary,
                shadowOpacity: 0.3,
                shadowRadius: 14,
                shadowOffset: { width: 0, height: 6 },
                elevation: 5,
                opacity: pressed ? 0.92 : 1,
              })}
            >
              <LinearGradient
                colors={["#5FAE72", tokens.color.primary, tokens.color.primaryDark]}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 1 }}
                style={{
                  flexDirection: "row",
                  alignItems: "center",
                  minHeight: 62,
                  paddingHorizontal: 10,
                  gap: tokens.space[3],
                }}
              >
                <View
                  style={{
                    width: 42,
                    height: 42,
                    borderRadius: 21,
                    backgroundColor: tokens.color.onPrimary,
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  <AppText style={{ fontSize: 18, color: tokens.color.primary }}>→</AppText>
                </View>
                <View style={{ gap: 1 }}>
                  <AppText variant="h3" style={{ color: tokens.color.onPrimary }}>Get Started</AppText>
                  <AppText variant="bodySm" style={{ color: tokens.color.onPrimary, opacity: 0.9, fontSize: 11 }}>
                    Join thousands making a difference
                  </AppText>
                </View>
              </LinearGradient>
            </Pressable>

            <View style={{ alignItems: "center", gap: 1 }}>
              <View style={{ flexDirection: "row", alignItems: "center", gap: 5 }}>
                <FeatureIcon feature="certified" size={13} />
                <AppText variant="bodySm" style={{ fontWeight: "600", fontSize: 12 }}>Trusted by Thousands</AppText>
              </View>
              <AppText variant="label" tone="muted" style={{ fontSize: 8 }}>
                Secure  •  Fast  •  Eco Friendly
              </AppText>
            </View>
          </View>
        </View>
      </View>
    </PortalThemeProvider>
  );
}
