import { Pressable, View } from "react-native";
import { useRouter, type Href } from "expo-router";
import {
  AppText, Card, IconTile, PORTAL_ACCENTS, PortalThemeProvider, Screen, tokens,
} from "@rebin/ui";
import { PORTAL_CONTENT, PORTAL_ORDER } from "../src/config/portals";

// Same reasoning as RoleGuard.tsx's `asHref` (apps/mobile/src/components/
// RoleGuard.tsx): Expo Router's typed-routes codegen (apps/mobile/.expo/
// types/router.d.ts) is generated by running the Expo dev server/CLI, not by
// `tsc`, and the checked-in snapshot predates this task's new routes
// ("/portal/[role]" itself, plus "/login" and "/catalog", both destinations
// with no screen file yet — out of this task's scope). Every string passed
// through this cast is a hand-authored, known route name, never unvalidated
// input, so this only defers path-existence checking to whichever task adds
// those screens/regenerates the codegen, not a real type-safety hole.
function asHref(path: string): Href {
  return path as Href;
}

export default function Index() {
  const router = useRouter();
  return (
    <PortalThemeProvider portal="org">
      <Screen>
        <View style={{ gap: tokens.space[1], marginBottom: tokens.space[2] }}>
          <AppText variant="label" tone="muted">REBIN TECH</AppText>
          <AppText variant="display">Free, compliant{"\n"}e-waste recycling</AppText>
          <AppText variant="body" tone="muted">Choose how you want to get started.</AppText>
        </View>

        {PORTAL_ORDER.map((key) => {
          const p = PORTAL_CONTENT[key];
          return (
            <PortalThemeProvider key={key} portal={key}>
              <Pressable
                accessibilityRole="button"
                accessibilityLabel={`${p.title}. ${p.tagline}`}
                onPress={() => router.push(asHref(`/portal/${key}`))}
              >
                <Card accentBorder style={{ gap: tokens.space[2] }}>
                  <View style={{ flexDirection: "row", alignItems: "center", gap: tokens.space[2] }}>
                    <IconTile />
                    <View style={{ flex: 1, gap: 2 }}>
                      <AppText variant="h1">{p.title}</AppText>
                      <AppText variant="h3" tone="accent">{p.tagline}</AppText>
                    </View>
                  </View>
                  <View style={{ alignSelf: "flex-start", paddingHorizontal: tokens.space[2], paddingVertical: 6, borderRadius: tokens.radius.chip, borderWidth: 1, borderColor: PORTAL_ACCENTS[key] }}>
                    <AppText variant="label" tone="accent">{p.badge}</AppText>
                  </View>
                  <AppText variant="bodySm" tone="muted">{p.description}</AppText>
                </Card>
              </Pressable>
            </PortalThemeProvider>
          );
        })}

        <View style={{ gap: tokens.space[1], marginTop: tokens.space[2] }}>
          <Pressable accessibilityRole="button" accessibilityLabel="Browse Price Catalog" onPress={() => router.push(asHref("/catalog"))} style={{ minHeight: 44, justifyContent: "center" }}>
            <AppText tone="accent">Browse Price Catalog ($/lb rates)</AppText>
          </Pressable>
          <Pressable accessibilityRole="button" accessibilityLabel="Log In" onPress={() => router.push(asHref("/login"))} style={{ minHeight: 44, justifyContent: "center" }}>
            <AppText tone="muted">Already have an account? <AppText tone="accent">Log In</AppText></AppText>
          </Pressable>
        </View>
      </Screen>
    </PortalThemeProvider>
  );
}
