import { Pressable, View } from "react-native";
import { useRouter, type Href } from "expo-router";
import Svg, { Circle, Path, Rect } from "react-native-svg";
import {
  AppText, IconTile, PORTAL_ACCENTS, PortalThemeProvider, Screen, tokens,
} from "@rebin/ui";
import { PORTAL_CONTENT, PORTAL_ORDER } from "../../src/config/portals";

// Same reasoning as RoleGuard.tsx's `asHref`: Expo Router's typed-routes
// codegen is generated by the dev server, not `tsc`, and the checked-in
// snapshot predates these routes. Every string passed through is a
// hand-authored, known route name, never unvalidated input.
function asHref(path: string): Href {
  return path as Href;
}

type PortalKey = (typeof PORTAL_ORDER)[number];

// Literal icons for *what's actually collected* from each audience — office
// electronics, board-level scrap, a dispatch vehicle — so the row itself
// answers "what do I bring you?"
function PortalIcon({ portal, color, size = 26 }: { portal: PortalKey; color: string; size?: number }) {
  if (portal === "org") {
    return (
      <Svg width={size} height={size} viewBox="0 0 26 26" fill="none">
        <Rect x="3" y="4" width="20" height="14" rx="2" stroke={color} strokeWidth="2" />
        <Rect x="7" y="7" width="12" height="8" rx="1" fill={color} opacity={0.25} />
        <Path d="M9 22h8M13 18v4" stroke={color} strokeWidth="2" strokeLinecap="round" />
      </Svg>
    );
  }
  if (portal === "business") {
    return (
      <Svg width={size} height={size} viewBox="0 0 26 26" fill="none">
        <Rect x="6" y="6" width="14" height="14" rx="2" stroke={color} strokeWidth="2" />
        <Rect x="10" y="10" width="6" height="6" rx="1" fill={color} opacity={0.3} />
        <Path
          d="M9 3v3M13 3v3M17 3v3M9 20v3M13 20v3M17 20v3M3 9h3M3 13h3M3 17h3M20 9h3M20 13h3M20 17h3"
          stroke={color}
          strokeWidth="1.6"
          strokeLinecap="round"
        />
      </Svg>
    );
  }
  return (
    <Svg width={size} height={size} viewBox="0 0 26 26" fill="none">
      <Path d="M3 9h13v9H3z" stroke={color} strokeWidth="2" strokeLinejoin="round" />
      <Path d="M16 12h4l3 3v3h-7z" stroke={color} strokeWidth="2" strokeLinejoin="round" />
      <Circle cx="8" cy="20" r="2" stroke={color} strokeWidth="2" />
      <Circle cx="19" cy="20" r="2" stroke={color} strokeWidth="2" />
    </Svg>
  );
}

export default function PortalSelect() {
  const router = useRouter();
  return (
    <PortalThemeProvider portal="org">
      <Screen>
        <View style={{ gap: 4, marginBottom: tokens.space[2] }}>
          <AppText variant="h1">Who are you recycling as?</AppText>
          <AppText variant="bodySm" tone="muted">
            Each path has its own signup, pricing, and tools.
          </AppText>
        </View>

        <View>
          {PORTAL_ORDER.map((key, i) => {
            const p = PORTAL_CONTENT[key];
            return (
              <PortalThemeProvider key={key} portal={key}>
                <Pressable
                  accessibilityRole="button"
                  accessibilityLabel={`${p.title}. ${p.tagline}`}
                  onPress={() => router.push(asHref(`/portal/${key}`))}
                  style={({ pressed }) => ({
                    flexDirection: "row",
                    alignItems: "center",
                    gap: tokens.space[3],
                    paddingVertical: tokens.space[3],
                    borderTopWidth: i === 0 ? 0 : 1,
                    borderTopColor: tokens.color.divider,
                    opacity: pressed ? 0.6 : 1,
                  })}
                >
                  <IconTile size={48}>
                    <PortalIcon portal={key} color={PORTAL_ACCENTS[key]} />
                  </IconTile>
                  <View style={{ flex: 1, gap: 1 }}>
                    <AppText variant="h3">{p.title}</AppText>
                    <AppText variant="bodySm" tone="accent">{p.tagline}</AppText>
                    <AppText variant="label" tone="muted" style={{ fontSize: 9 }}>{p.badge}</AppText>
                  </View>
                  <AppText style={{ fontSize: 18, color: tokens.color.muted }}>›</AppText>
                </Pressable>
              </PortalThemeProvider>
            );
          })}
        </View>

        <View style={{ flexDirection: "row", alignItems: "center", gap: tokens.space[2], marginVertical: tokens.space[3] }}>
          <View style={{ flex: 1, height: 1, backgroundColor: tokens.color.divider }} />
          <AppText variant="bodySm" tone="muted">or</AppText>
          <View style={{ flex: 1, height: 1, backgroundColor: tokens.color.divider }} />
        </View>

        <View style={{ gap: tokens.space[1] }}>
          <Pressable accessibilityRole="button" accessibilityLabel="Browse Price Catalog" onPress={() => router.push(asHref("/catalog"))} style={{ minHeight: 44, justifyContent: "center", alignItems: "center" }}>
            <AppText variant="bodySm" tone="accent">Browse Price Catalog ($/lb rates)</AppText>
          </Pressable>
          <Pressable accessibilityRole="button" accessibilityLabel="Log In" onPress={() => router.push(asHref("/login"))} style={{ minHeight: 44, justifyContent: "center", alignItems: "center" }}>
            <AppText variant="bodySm" tone="muted">Already have an account? <AppText variant="bodySm" tone="accent">Log In</AppText></AppText>
          </Pressable>
        </View>
      </Screen>
    </PortalThemeProvider>
  );
}
